### ISSUE TITLE
The bottom of the Plug is clipped in Japanese environment

### ISSUE THREAD

**Issue by ryonakano** [elementary/switchboard-plug-onlineaccounts#108]
![Screenshot from 2019-08-22 22-27-07](https://user-images.githubusercontent.com/26003928/63522173-cb381e00-c532-11e9-86b3-8457c22781c0.png)

Before I translated the string "Connect online accounts by clicking the icon in the toolbar below." (in [this commit](https://github.com/elementary/switchboard-plug-onlineaccounts/commit/33a362b487fcde8e549202fd8cdad50a07615417)), the UI is shown correctly in Japanese environment.

![Screenshot from 2019-08-22 22-26-28](https://user-images.githubusercontent.com/26003928/63522171-cb381e00-c532-11e9-845a-3ed9e044902e.png)

![Screenshot from 2019-08-22 23-18-59](https://user-images.githubusercontent.com/26003928/63522409-3e419480-c533-11e9-80f9-fad8fe79b637.png)

However, after that commit, the bottom of Plug is clipped in Japanese environment. Even if I maximize the window the action bar is not shown so that I can't add any online accounts. I tested `master` but had no luck. If I run `LANG=C io.elementary.switchboard` to show System Settings in English, the UI is shown correctly.

To confirm the issue, just run `LANGUAGE=ja io.elementary.switchboard`.

**Comment by hanaral** [comment]
The plug it still looks like this on Odin daily:
![Screenshot from 2020-09-21 16-06-48](https://user-images.githubusercontent.com/58219504/93784442-ed640a00-fc24-11ea-803c-c421b924380a.png)

**Comment by davidmhewitt** [comment]
Changing the wrap mode on the title label in the Granite alert view to `WORD` instead of `WORD_CHAR` seems to help with this. Though I'm not sure why the size allocations of the right pane are affecting the left pane.
