### ISSUE TITLE
Issues with this plug in dowstreams

### ISSUE THREAD

**Issue by worldofpeace** [elementary/switchboard-plug-onlineaccounts#114]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
I've walking around this issue for a while, and it appears in every downstream that has the Latest Pantheon Online Accounts stack, meaning the latest dbus interface changes from Signond, it just isn't working.

See:
* https://github.com/NixOS/nixpkgs/issues/54557
* https://github.com/decathorpe/elementary-nightly-rpms/issues/45

Both reports emit some errors regarding permissions issues.

I'm not sure if I should be reporting in https://gitlab.com/accounts-sso, but we have @tintou here anyway. If it turns out to be an issue there it should be easy to redirect this.

### To Reproduce
1. Select a provider within the plug
2. Enter your credentials
3. Submit them
4. Watch it fail with those errors.

Here are the version of all the Accounts SSO related things in NixOS:
- libsignon-glib: 2.1
- gsignond: 1.2.0
- libaccounts-glib: 1.24
- gsignond-plugin-mail: 0.3.0
- gsignond-plugin-lastfm: https://gitlab.com/accounts-sso/gsignond-plugin-lastfm/commit/0a7a5f8511282e45cfe35987b81f27f158f0648c
- signon-plugin-sasl: https://gitlab.com/accounts-sso/gsignond-plugin-sasl/commit/b304c70b7dad9368b23b1205122d10de684c896a
- signon-plugin-oauth2: https://gitlab.com/accounts-sso/gsignond-plugin-oa/commit/d471cebfd7c50567b1244277a9559f18f8d58691

### Expected behavior
Kinda obvious here :smile: 

### Screenshots or screen recordings
I've already entered credentials with Last.fm here.
![Peek 2019-09-27 15-28](https://user-images.githubusercontent.com/28888242/65796761-71cb9c00-e13b-11e9-9ace-c1919c1348fa.gif)

### Logs
See aforementioned downstream reports.

They seem to be different between NixOS and fedora 

##### NixOS
```
 Account.vala:103: GDBus.Error:com.google.code.AccountsSSO.gSingleSignOn.Error.PermissionDenied: Can not read identity
```

##### Fedora
```
** (io.elementary.switchboard:5044): CRITICAL **: 19:18:50.626: PasswordProvider.vala:74: GDBus.Error:com.google.code.AccountsSSO.gSingleSignOn.Error.PermissionDenied: identity can not be accessed
```

Example here isn't with the lastfm plugin, it appears that plugin wasn't installed from the errors.
So I ruled it out.

- [x] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by worldofpeace** [comment]
cc @decathorpe.

I'd be helpful if you could provide information like if this is still reproducible.

**Comment by decathorpe** [comment]
I was at least able to successfully authenticate and add a Microsoft account with the plug built from git on fedora 30. I didn't test other account types (I don't have Last.fm or Facebook accounts, and I don't want to use my private Google account for testing).

**Comment by worldofpeace** [comment]
Just tried microsoft on git master and latest release with the same issue.

Do you have a different Signond versions in Rawhide?

**Comment by decathorpe** [comment]
I haven't checked rawhide. but gsignond and libsignon-glib versions should be the same on fedora 30 as the ones you listed above

**Comment by worldofpeace** [comment]
Hmm, not really pleased with how I opened this report. Not really actionable and I'm thinking it's possibly an issue for Accounts SSO. I'll close this and move it to that tracker.
