### ISSUE TITLE
Use Handy.Leaflet in add account dialog

### ISSUE THREAD

**Issue by danrabbit** [elementary/switchboard-plug-onlineaccounts#118]
So we get nice swipe gestures

**Comment by Exalm** [comment]
I'm not sure you want leaflet here, it would look something like this when unfolded:

![Screenshot from 2019-12-12 21-20-47](https://user-images.githubusercontent.com/1510457/70729763-b0650180-1cfb-11ea-8323-7de59d0f7e80.png)

**Comment by danrabbit** [comment]
Gonna close this because we're gonna do something else
