### ISSUE TITLE
Online accounts support just like Gnome(Or better)

### ISSUE THREAD

**Issue by hackstash** [elementary/switchboard-plug-onlineaccounts#141]
## Problem

There is no online account support for Google, Microsoft or Drop box. No one uses fast-mail and last.fm. Most of the users have Gmail and Outlook accounts.

## Proposal

I can understand that you guys must be busy in eOS 6 development. Also adding support and integrating these features might not be easy as it sounds. But guys this is my humble request to team elementary to consider adding support to Gdrive , Gmail and Onedrive just like Gnome.

**Comment by RavetcoFX** [comment]
I'm curious about this as well, and I have no clue how to add more account services on the latest 6.0 daily build

![Screenshot from 2021-03-10 13-07-52](https://user-images.githubusercontent.com/1816681/110691006-d2209300-81a1-11eb-8199-f3e985298a01.png)

**Comment by RavetcoFX** [comment]
You need to install pantheon-online-accounts-plugin-google pantheon-online-accounts-microsoft but at the moment there is no Dropbox

**Comment by kdwk** [comment]
** (io.elementary.switchboard:11560): CRITICAL **: 21:06:37.115: Account.vala:103: GDBus.Error:com.google.code.AccountsSSO.gSingleSignOn.Error.MethodNotKnown: authentication method 'oauth' doesn't exist

@RavetcoFX Seems like pantheon-online-accounts-plugin-google does not work. Also, pantheon-online-accounts-microsoft doesn't seem to exist
