### ISSUE TITLE
Option for popular accounts

### ISSUE THREAD

**Issue by kdwk** [elementary/switchboard-plug-onlineaccounts#148]
Duplicate of #141, providing more information and explaining how the current implementation does not work.
## Problem

The current choice of accounts... limited. It lacks popular and mainstream services like Google, Microsoft (both personal and exchange) and Nextcloud. Since Mail provides no other way of signing in, users are basically stuck with an alternative mail client. Even if Mail allows signing in to other services, it would bypass switchboard-plug-onlineaccounts, making it pointless.

In #141 it is suggested that we install: pantheon-online-accounts-plugin-google pantheon-online-accounts-microsoft

First, pantheon-online-accounts-microsoft does not exist. Second, pantheon-online-accounts-plugin-google does not work because it is rely on OAuth, which does not exist in elementary OS.

## Proposal

Include gnome-online-accounts, or re-implement it to support OAuth services such as Google, Microsoft and Nextcloud.

## Prior Art

https://gitlab.gnome.org/GNOME/gnome-online-accounts
![image](https://user-images.githubusercontent.com/39268094/116775001-d81f4b80-aa4f-11eb-9f62-db395098018f.png)

**Comment by danrabbit** [comment]
Closing as too broad. This issue report contains multiple action items and needs to be broken up. There are already existing issues for Google and Nextcloud. Please file separate issue reports for each specific additional online service
