### ISSUE TITLE
Passwords aren't saved for Imap

### ISSUE THREAD

**Issue by danrabbit** [elementary/switchboard-plug-onlineaccounts#172]
## What Happened

We ask for passwords on account creation, but they don't appear to actually be saved. I get password dialogs when opening Mail after adding accounts here

## Expected Behavior

Passwords should be saved, so no dialogs

## Steps to Reproduce

1. Add a Mail account
2. Open Mail or Evolution
3. Get a password dialog

**Comment by marbetschar** [comment]
@danrabbit I won't be online at the weekend, so I'm unable to look into this till Monday. However, maybe [`E.SourceCredentialsProvider`](https://valadoc.org/libedataserver-1.2/E.SourceCredentialsProvider.store.html) works better than the `E.Source.store_password`?

You might want to give something like this a try:

```
var credentials = new E.NamedParameters ();
credentials.set (E.SOURCE_CREDENTIAL_USERNAME, username);
credentials.set (E.SOURCE_CREDENTIAL_PASSWORD, password);

var credentials_provider = new E.SourceCredentialsProvider (registry);
try {
    yield credentials_provider.store (mail_send_source, credentials, true, cancellable);
} ...
```

... same for mail_account_source (IMAP) of course.

**Comment by danrabbit** [comment]
Hm, I didn't seem to have any luck with that, but I might be missing something!

**Comment by danrabbit** [comment]
Possibly related, I get this error in Mail `MailBackendSimpleSasl has an empty CamelServiceAuthType`
