### ISSUE TITLE
Unmet dependencies

### ISSUE THREAD

**Issue by shawn1thompson** [elementary/switchboard-plug-onlineaccounts#182]
## What Happened
I'm getting the following when I try to update:

The following packages have unmet dependencies:
  pantheon-online-accounts-plugin-lastfm: Depends: switchboard-plug-online-accounts (= 2.0.1+r925+pkg63~daily~ubuntu6.1) but 3.0.0+r33+pkg65~daily~ubuntu6.1 is to be installed
  pantheon-online-accounts-plugin-fastmail: Depends: switchboard-plug-online-accounts (= 2.0.1+r925+pkg63~daily~ubuntu6.1) but 3.0.0+r33+pkg65~daily~ubuntu6.1 is to be installed
  pantheon-online-accounts-plugin-mail: Depends: switchboard-plug-online-accounts (= 2.0.1+r925+pkg63~daily~ubuntu6.1) but 3.0.0+r33+pkg65~daily~ubuntu6.1 is to be installed

## Expected Behavior
Update without error

## Steps to Reproduce

1. Open App Center
2.Update all

## Platform Information
Odin 6.0

**Comment by ryonakano** [comment]
You can fix it by running:

```bash
sudo apt purge -y pantheon-online-accounts-plugin-lastfm pantheon-online-accounts-plugin-fastmail pantheon-online-accounts-plugin-mail && sudo apt autoremove
```

**Comment by shawn1thompson** [comment]
I'm assuming that I have to reinstall the apps that were uninstalled by autoremove then?

**Comment by shawn1thompson** [comment]
I went ahead and reinstalled using:

apt install io.elementary.calculator io.elementary.mail io.elementary.screenshot io.elementary.tasks io.elementary.camera

Updates went fine, saw the new-ish experience in Online Accounts, and it appeared I was able to add an IMAP account, but it wasn't recognized in Mail. Tried again to add the account by going to Account settings in Mail, but to no avail; the account doesn't appear to be saved.

**Comment by ryonakano** [comment]
> apt install io.elementary.calculator io.elementary.mail io.elementary.screenshot io.elementary.tasks io.elementary.camera

You don't need to run this and it's safe to autoremove these apps because they're now provided as a Flatpak package.

The new re-writed Online Accounts Plug is still work in progress, so there should be some issues. I assume your issue that the account is not recognized in Mail is #172.

**Comment by shawn1thompson** [comment]
Nice. So, are they installable from Flathub? Should I install from there?

Also, the issue looks similar, but I'm not sure it's exactly the same. The whole account isn't saved for me, not just the password.

**Comment by ryonakano** [comment]
Nope, it's not in Flathub but instead in the elementary remote. You may want to run:

```
flatpak install io.elementary.calculator io.elementary.mail io.elementary.screenshot io.elementary.tasks io.elementary.camera
```

Maybe you're seeing a dialog that asks your email and password when you open Mail, and if you click either save or cancel, the dialog appears again and again, right? If so, I guess your issue is #172; actually I also faced this issue when I tried the new plug like you just a couple of days ago.

**Comment by shawn1thompson** [comment]
I'm still updating my Early Access. I'll install those tomorrow and update. Thank you.

**Comment by shawn1thompson** [comment]
I tried installing via flatpak install, but the flatpak remote wasn't set in the system. I couldn't find a way to set it; so, I just wiped and installed the Beta. I ran into the same error when updating, but was able to resolve using the previous instructions. Thanks.
