### ISSUE TITLE
MailBackendSimpleSasl has an empty CamelServiceAuthType

### ISSUE THREAD

**Issue by danrabbit** [elementary/switchboard-plug-onlineaccounts#185]
## What Happened

I keep getting this error when opening Mail with accounts added from here:

`MailBackendSimpleSasl has an empty CamelServiceAuthType`

## Expected Behavior

I supposed we need to set the authentication type somewhere

## Steps to Reproduce

1. Add an IMAP account with online accounts
2. run Mail from terminal
3. See this error

**Comment by marbetschar** [comment]
This should be fixed once https://github.com/elementary/mail/pull/627 is merged. Can you confirm?

**Comment by marbetschar** [comment]
This has been fixed by https://github.com/elementary/mail/pull/681.
