### ISSUE TITLE
Compilation failed: The name `error_quark` does not exist in the context of `Camel.Service`

### ISSUE THREAD

**Issue by bobby285271** [elementary/switchboard-plug-onlineaccounts#198]
I am trying to package [6.1.0](https://github.com/elementary/switchboard-plug-onlineaccounts/tree/0243c519e3576b49d50ade6394356b9aa2ae9b68) on NixOS and the compilation failed with:

Full log: https://gist.github.com/bobby285271/8cc47f943f251a1353bcbde69c10411a

```
../src/Dialogs/Imap/ImapDialog.vala:432.21-432.45: error: The name `error_quark' does not exist in the context of `Camel.Service' (camel-1.2)
                    Camel.Service.error_quark (),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
```

I was able to build 6.0.0 on the same environment.

Shall we add a `vapi/camel-1.2.vapi` file like [elementary/mail](https://github.com/elementary/mail/blob/master/vapi/camel-1.2.vapi) does? Seems that the problem can be solved by doing this, see [my fork](https://github.com/bobby285271/switchboard-plug-onlineaccounts/commit/400535bfc1069e5f73cb71023752e5bb74ca743d) for more details.

Related: https://github.com/NixOS/nixpkgs/pull/130380#issuecomment-890344969

Thanks for reading this :-)

UPD: Just opened a PR for this.

**Comment by decathorpe** [comment]
I'm having the same problem on Fedora. Release 6.0.0 built fine, Release 6.1.0 fails. Looks like this PR is the culprit:
https://github.com/elementary/switchboard-plug-onlineaccounts/pull/189
