### ISSUE TITLE
Unacceptable TLS certificate

### ISSUE THREAD

**Issue by shawn1thompson** [elementary/switchboard-plug-onlineaccounts#199]
## What Happened

Received **Unacceptable TLS certificate**. Note: I'm using ProtonMail's ProtonMail Bridge.

## Expected Behavior

Account should be added.

## Steps to Reproduce

1. Deleted ProtonMail IMAP account in Online Accounts. 
2. Added it back.
3. Received Unacceptable TLS certificate.

### Logs

Unacceptable TLS certificate

## Platform Information

Elementary OS 6 (Odin) Beta 2

**Comment by MrPaulBlack** [comment]
This is because the protonmail bridge creates a IMAP and SMTP server on localhost with a self signed cert. So the ability to add a security exception or accept the self singned cert would be great to be able to use protonmail bridge with the elementary online accounts integration.

**Comment by shawn1thompson** [comment]
No longer using Elementary of Proton and will be unable to troubleshoot if needed.

**Comment by ericpritchett** [comment]
I found a solution and have the steps listed at https://github.com/elementary/switchboard-plug-onlineaccounts/issues/257#issuecomment-1605878593
