### ISSUE TITLE
Cannot add IMAP account with no encryption (none)

### ISSUE THREAD

**Issue by dmanlfc** [elementary/switchboard-plug-onlineaccounts#203]
## What Happened
If you try to add an IMAP account which doesn't require encryption you get the error suggesting the 'server does not support PLAIN authentication', although it does work fine with Mailspring & Thunderbird mail clients.

## Expected Behavior
Expecting to be able to create an account

## Steps to Reproduce

1. Create a Davmail server connecting to an Exchange instance
2. Verify it works with another client.
3. Try to connect the Elementary OS mail client to the local Davmail server (127.0.0.1) without TLS or SSL
4. Failure message as per above.

## Platform Information
* The version of elementary OS you are using, or other operating system - 6 stable (10th Aug)
* The version of the software you are using - Mail v6.1 (July 28)

**Comment by Brutalious** [comment]
Same issue here.
![Schermafdruk van 2021-08-15 23 24 50](https://user-images.githubusercontent.com/48983670/129493375-f6cee1b4-76bc-44d7-998c-8f84a06d7207.png)
