### ISSUE TITLE
MAILSPRING not syncing with IONOS/ 1and1 on Mac desktop 

### ISSUE THREAD

**Issue by JBblksq** [elementary/switchboard-plug-onlineaccounts#204]
## What Happened
For two days Mailspring has not worked on my Mac. Email server is IONOS, I get emails on my phone through Gmail. 

## Expected Behavior
I cannot see new emails on Mailspring desktop. I cannot send emails. 

## Steps to Reproduce

1. Mailspring "encountered error while syncing my email"
2. Try reconnect IMAP in Preferences, not successful
3. Try re-installing Mailspring on desktop, not successful

### Logs
Error details:

Mailspring Version: 1.9.1-30ef802f
Platform: darwin
Account State: sync_error
Account Provider: imap
IMAP Server: imap.1and1.com
SMTP Server: smtp.1and1.com
--------------------------------------------
***
*** Mailspring Sync 
*** A C++ exception occurred during program execution: 
*** database disk image is malformed
***

49153 [2021-08-11 17:14:40.933] [background] [critical] *** Stack trace (line numbers are approximate):
*** in mailsync     exceptions::logCurrentExceptionWithStackTrace()
*** in mailsync     runBackgroundSyncWorker()
*** in mailsync     main::$_6::operator()() const
*** in mailsync     void* __thread_proxy(void*)
*** 0x7fff20612443  thread_start()
***

49156 [2021-08-11 17:14:41.065] [main] [info] Identity created at 1578045016 - using ID Schema 1
49156 [2021-08-11 17:14:41.066] [main] [info] ------------- Starting Sync (jill@blksq.com) ---------------
49156 [2021-08-11 17:14:41.071] [background] [info] Marking all folders as `busy`
49156 [2021-08-11 17:14:41.071] [metadata] [info] Metadata delta stream starting...
49156 [2021-08-11 17:14:41.072] [background] [info] Syncing folder list...
49156 [2021-08-11 17:14:41.531] [background] [info] Syncing folder list...
49156 [2021-08-11 17:14:41.618] [background] [info] syncFolderUIDRange for INBOX, UIDs: 3228 - 3240, Heavy: true
49156 [2021-08-11 17:14:41.756] [background] [info] - remote=10, local=0
49156 [2021-08-11 17:14:41.757] [background] [critical] 
***
*** Mailspring Sync 
*** A C++ exception occurred during program execution: 
*** database disk image is malformed
***

49156 [2021-08-11 17:14:41.818] [background] [critical] *** Stack trace (line numbers are approximate):
*** in mailsync     exceptions::logCurrentExceptionWithStackTrace()
*** in mailsync     runBackgroundSyncWorker()
*** in mailsync     main::$_6::operator()() const
*** in mailsync     void* __thread_proxy(void*)
*** 0x7fff20612443  thread_start()
***

49159 [2021-08-11 17:14:42.068] [main] [info] Identity created at 1578045016 - using ID Schema 1
49159 [2021-08-11 17:14:42.068] [main] [info] ------------- Starting Sync (jill@blksq.com) ---------------
49159 [2021-08-11 17:14:42.073] [background] [info] Marking all folders as `busy`
49159 [2021-08-11 17:14:42.074] [metadata] [info] Metadata delta stream starting...
49159 [2021-08-11 17:14:42.074] [background] [info] Syncing folder list...
49159 [2021-08-11 17:14:42.549] [background] [info] Syncing folder list...
49159 [2021-08-11 17:14:42.638] [background] [info] syncFolderUIDRange for INBOX, UIDs: 3228 - 3240, Heavy: true
49159 [2021-08-11 17:14:42.770] [background] [info] - remote=10, local=0
49159 [2021-08-11 17:14:42.771] [background] [critical] 
***
*** Mailspring Sync 
*** A C++ exception occurred during program execution: 
*** database disk image is malformed
***

49159 [2021-08-11 17:14:42.830] [background] [critical] *** Stack trace (line numbers are approximate):
*** in mailsync     exceptions::logCurrentExceptionWithStackTrace()
*** in mailsync     runBackgroundSyncWorker()
*** in mailsync     main::$_6::operator()() const
*** in mailsync     void* __thread_proxy(void*)
*** 0x7fff20612443  thread_start()
***

## Platform Information
<img width="510" alt="Screen Shot 2021-08-11 at 5 24 40 PM" src="https://user-images.githubusercontent.com/88806040/129116174-f0681bff-282c-4ef3-b7ea-bfe93e03793d.png">

<img width="263" alt="Screen Shot 2021-08-11 at 5 25 40 PM" src="https://user-images.githubusercontent.com/88806040/129116227-cc7fbacf-3cfc-467c-8069-62612de899eb.png">

**Comment by danrabbit** [comment]
Hey there, it seems like you're a little lost! This issue tracker is neither for Mailspring or for macOS. This is an issue tracker for an operating system called elementary OS

Closing this issue report because it's about an app we don't make on an OS we don't make :)

**Comment by JBblksq** [comment]
OopsOn Aug 11, 2021 5:31 PM, Daniel Foré ***@***.***> wrote:
Hey there, it seems like you're a little lost! This issue tracker is neither for Mailspring or for macOS. This is an issue tracker for an operating system called elementary OS
Closing this issue report because it's about an app we don't make on an OS we don't make :)
