### ISSUE TITLE
Cannot sync Mailo and Yahoo IMAP

### ISSUE THREAD

**Issue by mathessaricci** [elementary/switchboard-plug-onlineaccounts#206]
I tried several times using all configurations specified by the Mailo and the Yahoo services. But the unique account I could sync was the Gmail one.
I also tried syncing directly on the Geary (flathub) app and it works completely fine.

**Comment by marbetschar** [comment]
Possible duplicate of https://github.com/elementary/switchboard-plug-onlineaccounts/issues/203

**Comment by marbetschar** [comment]
@mathessaricci since https://github.com/elementary/switchboard-plug-onlineaccounts/pull/211 is released by now, is this still an issue for you? Or does it work now?

**Comment by mathessaricci** [comment]
It's working now. I'll close the issue. Thanks for remind me!
