### ISSUE TITLE
Add JMAP support

### ISSUE THREAD

**Issue by chriskilding** [elementary/switchboard-plug-onlineaccounts#212]
JMAP (JSON Meta Application Protocol) is a modern open PIM syncing protocol. Fastmail developed it to overcome the problems inherent in IMAP, and (presumably) to provide a credible open alternative to proprietary PIM sync protocols like Exchange ActiveSync.

JMAP is now an IETF Internet Standard:

- RFC8620 (https://datatracker.ietf.org/doc/html/rfc8620): JMAP
- RFC8621 (https://datatracker.ietf.org/doc/html/rfc8621): JMAP for Mail

Some other RFCs are also in development to cover other applications of JMAP:

- draft-ietf-jmap-calendars-06 (https://datatracker.ietf.org/doc/draft-ietf-jmap-calendars/): JMAP for Calendars
- draft-ietf-jmap-tasks-00 (https://datatracker.ietf.org/doc/draft-ietf-jmap-tasks/): JMAP for Tasks

Therefore it would be good if this Elementary Switchboard plug (as well as Mail / Calendar etc) could support JMAP-based accounts.

The following things already implement JMAP:

- Fastmail.com service
- Topicbox service
- Cyrus mail server (which Fastmail is based on)

**Comment by chriskilding** [comment]
Blog post about it: https://fastmail.blog/open-technologies/jmap-new-email-open-standard/

(May offer easier reading than an RFC)

**Comment by cassidyjames** [comment]
We don't implement the mail backend; it's provided by the [Evolution Data Server](https://gitlab.gnome.org/GNOME/evolution-data-server). JMAP support would need to be added there first before we're able to utilize it here.
