### ISSUE TITLE
Some calendars not syncing

### ISSUE THREAD

**Issue by shawn1thompson** [elementary/switchboard-plug-onlineaccounts#213]
## What Happened

I am using the EteSync Dav Bridge. I added the DAV account to Online accounts successfully, but in Calendar only two calendars are showing. All of my tasks are showing. Then, I installed the Evolution flatpak and added the DAV Collection Account in Evolution, but it only detected my contacts. Then, I added all the CardDAV and CalDAV accounts for contacts, calendars, and tasks to Evolution successfully, but the same issue persisted, i.e., everything shows up except the same two calendars. All of these do sync on my phone without issue.

## Expected Behavior

To be able to add the account in Online Accounts and for the calendars to sync and show in Calendar and Tasks

## Steps to Reproduce

1. Add the DAV account to Online accounts
2. Open Calendar see issue
3. Install Evolution flatpak
4. Add DAV Collection account
5. See issue in Evolution
6. Remove Collection account and add separate Card and Cal DAV accounts
7. See issue in Evolution

## Platform Information

elementary OS 6 Odin
Evolution 3.40.3 (by Flathub.org)

**Comment by shawn1thompson** [comment]
I did get all of the calendars to load in Thunderbird. Is there anything I can provide to help out with this? Thank you.

**Comment by marbetschar** [comment]
@shawn1thompson we [reworked the code a bit in terms of how calendars are discovered and added](https://github.com/elementary/switchboard-plug-onlineaccounts/pull/227) - maybe the change helps in this case as well. Can you test and report back after the next update of Online Accounts?

**Comment by shawn1thompson** [comment]
Could be, but my issue is with syncing, not discovering. I will still check though. Thanks.

**Comment by shawn1thompson** [comment]
I've removed and added the account again. Two things came up. First, my calendars show up in the Tasks app and in Calendar I'm getting the attached error for one of my calendars.


file:///home/gandalf/Pictures/Screenshots/calendar-issue.png

**Comment by shawn1thompson** [comment]
An update to onlineaccounts plugin was just installed. I removed the account and tried again and I'm back to the original issue.

**Comment by shawn1thompson** [comment]
The issue might have been due to some events that were causing trouble in the sync, but closing either way for lack of response and, unfortunately, moving away from Elementary due to needing a more up-to-date kernel for newer hardware.
