### ISSUE TITLE
Can't add scarlet.be IMAP account

### ISSUE THREAD

**Issue by marbetschar** [elementary/switchboard-plug-onlineaccounts#224]
## What Happened

@Brutalious reported they are not able to configure an IMAP account provided by `scarlet.be` and the following error is thrown from Online Accounts:

![131027836-25d06112-e167-46c9-8336-1b81210629fe](https://user-images.githubusercontent.com/392542/132454080-8ee3adf4-b849-4450-bc14-520ad5c93d92.png)

## Expected Behavior

The account should setup just like any other mail account.

### Logs

A quick research shows, there are quite a lot of clients out there struggling with this specific mail provider. Especially interesting is the K-9 issue because it does provide quite a lot of insight on why this happens:

- https://github.com/k9mail/k-9/issues/2648
- https://discussions.apple.com/thread/5270721

## Platform Information

elementary OS 6 Odin (stable).

**Comment by marbetschar** [comment]
@Brutalious any chance you can provide me a temporary scarlet.be mail box for testing?

Also please make sure to contact their support, since this seems to be a long standing issue with the `scarlet.be` server configuration as you can see from the above links (probably since 2013!).

**Comment by Brutalious** [comment]
@marbetschar I have send you all the login information via email, so you can use this for testing.

If I need to ask something specific to their contact support, just ask. Because I don't know exactly which questions I need to ask them.

IMAP information can be found [here](https://www.scarlet.be/help/faq/769/59/Welke-standaardinstellingen-gebruikt-Scarlet-voor-e-mail)

**Comment by marbetschar** [comment]
@Brutalious thanks, I've just tested the provided information and can reproduce the issue. Will investigate in the following days and report back once I tracked this down.

> If I need to ask something specific to their contact support, just ask. Because I don't know exactly which questions I need to ask them.

From [this comment](https://github.com/k9mail/k-9/issues/2648#issuecomment-320928994) it seems the scarlet server is advertising it supports the `PLAIN` auth method - but when doing an actual `PLAIN` authentication the server seems to reject the request. This, of course, is unexpected for the client application.

I need to digg into the specifics to confirm - but meanwhile you may just want to send the scarlet support the link to this issue, to raise awareness that there seems to be something wrong with their server configuration: There are several mail applications out there not working correctly with `scarlet.be` (at least [Apple Mail](https://discussions.apple.com/thread/5270721), [elementary Mail](https://github.com/elementary/switchboard-plug-onlineaccounts/issues/224) and [K-9 Mail](https://github.com/k9mail/k-9/issues/2648)).

So maybe scarlet can help fix things for good.

**Comment by marbetschar** [comment]
@Brutalious I digged into this and you definitely want to contact scarlet about it. This seems not to be related to elementary OS at all - but to some kind of missconfiguration at your provider. To verify this, I executed the following in the Terminal:

```
$ openssl s_client -quiet -connect imap.scarlet.be:993 -crlf
depth=2 OU = GlobalSign Root CA - R3, O = GlobalSign, CN = GlobalSign
verify return:1
depth=1 C = BE, O = GlobalSign nv-sa, CN = GlobalSign RSA OV SSL CA 2018
verify return:1
depth=0 C = BE, ST = Brussels Hoofdstedelijk Gewest, L = Evere, O = Scarlet Belgium NV, CN = *.scarlet.be
verify return:1
* OK IMAP4 Ready niles 00021630
1 LOGIN email-account@scarlet.be PasswordOfAccount
1 NO Could not determine server
```

As you can see the server responds with `Could not determine server`. A quick [research in the web examined](https://getmail.pyropus.narkive.com/XBSWh2Cv/imap-error-could-not-determine-server), this is probably due to the IMAP proxy not capable to figure out to which "real" IMAP server it should connect to to verify the credentials.

In addition, I also found [this thread](https://discussions.apple.com/thread/251909205) in Apple's forum from end of last year, also claiming scarlet's IMAP services are not working (the service was not working for those users from Oct 2020 until end of Dec 2020). Somehow this was solved back then - but no communication from Scarlet itself.

If I have to guess, I'd say they did not fix the root cause and you are running into the very same thing again here.

Will close this issue for now, since there is nothing we can do here.

**Comment by Brutalious** [comment]
@marbetschar I asked the costumer support of scarlet to look into this.

Only remark I'd like to make is that other software like Evolution & Thunderbird don't have this `PLAIN` connection error.

**Comment by marbetschar** [comment]
Interesting. I tested in Evolution as well and wasn't able to add the account there.

Anyway, feel free to re-open the issue if there's something specific we can do here - right now I don't have an idea how we can possibly fix this on our end.

Hopefully your provider can give us some more insights on this.
