### ISSUE TITLE
Can't set up for german e-mail provider "web.de"

### ISSUE THREAD

**Issue by SVYSHE** [elementary/switchboard-plug-onlineaccounts#226]
## What Happened
As I tried to set up my mail account I encountered the problem, that the application responded with "IMAP-Verification failed. Login failed. Please check your login credentials." (Self-translated from german to english).

I made sure that my provider allows to fetch the mails via IMAP and even tested it with geary, where it works.

The provider even provides the correct [settings](https://hilfe.web.de/pop-imap/imap/imap-serverdaten.html#indexlink_help_pop-imap_imap) for requesting via IMAP. I made sure to follow these although these are even the default settings Mail will fill in the inputs.

## Expected Behavior
I am able to receive my mail messages.

## Steps to Reproduce

1. Create an account on [web.de](https://web.de/)
2. Make sure in the online settings of your web.de account that you allowed fetching via IMAP.
2. Try to fetch your mails via "Mail" on elementaryOS

## Platform Information
- elementary OS 6 Odin
- Auf Basis von Ubuntu 20.04.3 LTS
- Linux 5.11.0-34-generic

**Comment by marbetschar** [comment]
I made a fix which potentially solves your issue: https://github.com/elementary/switchboard-plug-onlineaccounts/pull/225. Any chance you are able to confirm it works by compiling from source?

Please let me know if you need any guidance - I'm happy to help.

**Comment by marbetschar** [comment]
PS: If you'd rather not want to compile from source that's Ok too! Just let me know :)

**Comment by SVYSHE** [comment]
I possibly could but not today :/ 

I would suggest that I'll try to do it over the weekend :)

P.S.: I wanted to take a look at Vala anyways hehe :D

**Comment by SVYSHE** [comment]
Great news, I can confirm after building from source that it properly works now!

Thanks for your quick reaction :) And love to the humble vala community ;)

**Comment by marbetschar** [comment]
@SVYSHE glad to hear! 🥳
