### ISSUE TITLE
IMAP dialog missing title

### ISSUE THREAD

**Issue by cassidyjames** [elementary/switchboard-plug-onlineaccounts#234]
### What Happened?

I was entering my Mail password and had to alt+tab to copy+paste it. I noticed the window title was missing from the IMAP dialog, as visible in the new window switcher.

![Screenshot from 2021-11-22 11 25 18](https://user-images.githubusercontent.com/611168/142915823-a2812de4-e9b6-4356-a560-376554416f99.png)

### Steps to Reproduce

1. Start adding a new IMAP account
2. Alt+tab to see the window title

### Expected Behavior

The dialog doesn't show the fallback ID, but shows "IMAP" or similar

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by cassidyjames** [comment]
Oh, comparing this to the CalDAV dialog, the solution might actually be to make the IMAP dialog modal since modal dialogs don't show in the window switcher, anyway.

**Comment by danrabbit** [comment]
Possibly fixed in https://github.com/elementary/switchboard-plug-onlineaccounts/pull/233. Can you confirm @cassidyjames ?

**Comment by cassidyjames** [comment]
@danrabbit ah you're right. We should get this released. :sweat_smile:
