### ISSUE TITLE
support for evolution-data-server 3.45+ / libsoup-3

### ISSUE THREAD

**Issue by decathorpe** [elementary/switchboard-plug-onlineaccounts#243]
Starting with GNOME 43, some core components of the desktop have been ported to libsoup-3, which apparently brings a lot of new features, including HTTP/2 support. However, applications and libraries **cannot** load both libsoup-2.4 and libsoup-3 in the same process, as this is unsupported and will crash the application immediately.

This change indirectly affects switchboard-onlineaccounts, because evolution-data-server switched to libsoup-3 as of version 3.45.1, and that includes a few API changes. Most notably, there's an intentional change in libedataserver-1.2 / `E.SourceWebdav` that breaks builds of this project. I asked on the [Fedora development mailing list](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/FITD7MFN4V5LXXUFXFXOJTXDTGX7LAQV/) and got this response from the maintainer:

> the SoupURI structure is gone in libsoup3, there is used GUri
> instead. For that reason the ESourceWebdav has replaced the property with the
> "uri" property, using the GUri structure.

I'm not sure how the switch from libsoup-2.4 to libsoup-3 will affect other switchboard plus yet. But I think it will crash switchboard if it tries to load plugins that are linked against different libsoup, so the plugs might need to all add support for and be switched over to using libsoup-3 at the same time.

**Comment by korewaChino** [comment]
+1 This issue is also blocking Ultramarine Linux 37 releases.
