### ISSUE TITLE
Upgrade online accounts to system-wide

### ISSUE THREAD

**Issue by fayjie92** [elementary/switchboard-plug-onlineaccounts#269]
### Problem

Currently, elementary online accounts are limited. For example, Gmail is supported via oath2 app password. Outlook is messy. Moreover, it provides very basic online account services. 
Online accounts are vital for an operating system to claim to be a basic user OS. Gnome provides more accounts and has a seamless system-wide integrations. For example, gmail shows the calendar in gnome calendar and google drive is shown in files. 
On the other hand, elementary os is quite a pain to set-up online accounts. In 2023, it is falling behind by online accounts where most of the users use a gmail account or a Microsoft account. 

### Proposal

Use Gnome-online accounts in elementary os. Currently, elementary os uses the evolution data server. I belief, it will give users more account options, and a painful experience with elementary os while setting up the online accounts.

**Comment by danirabbit** [comment]
Thanks for your suggestion. It unfortunately isn't as easy as cherry picking components from other desktops. Google specifically requires special approval to use their oauth login.

As it is, this is not really an actionable issue report. You can file individual issues for specific things we could do to improve your experience with online accounts, but we're not able to import GNOME's online accounts settings into System Settings
