### ISSUE TITLE
Fastmail integration doesn't work

### ISSUE THREAD

**Issue by grvrulz** [elementary/switchboard-plug-onlineaccounts#37]
The Fastmail integration no longer works as the server addresses have changed. This has been fixed in #35 , but that bug fix is not released in any version. As of now, the Fastmail integration doesn't work at all. When trying to log in, it fails and Fastmail sends this email.

> You have just tried to log in to our IMAP service using an old server name such as mail.messagingengine.com, caldav.messagingengine.com or carddav.messagingengine.com.

> From the following address:

> geo [] ()

> These servers names no longer work and have been replaced by our new server names:

> IMAP - imap.fastmail.com, port=993, SSL/TLS enabled
> POP - pop.fastmail.com, port=995, SSL/TLS enabled
> SMTP - smtp.fastmail.com, port=465, SSL/TLS enabled
> CalDAV - https://caldav.fastmail.com/
> CardDAV - https://carddav.fastmail.com/
> WebDAV - https://webdav.fastmail.com/
> Please update your settings to use the correct server name.

According to the milestone on that particular bug, it is planned for release for Juno-beta-1. Since the integration doesn't work at all right now, it would make sense to remove it temporarily(or make a new release with the fix in #35 )

**Comment by danrabbit** [comment]
Assigning to Cody so he can make a new Online Accounts release for Loki

**Comment by danrabbit** [comment]
Closing as this was released August 18th

**Comment by grvrulz** [comment]
@danrabbit The version in stable still has the old settings

`$ cat /usr/share/accounts/services/fastmail-mail.service 
<?xml version="1.0" encoding="UTF-8"?>
<service id="fastmail-mail">
  <type>mail</type>
  <name>Email</name>
  <description>Sync your email</description>
  <icon>internet-mail</icon>
  <provider>fastmail</provider>
  <translations>pantheon-online-accounts</translations>

  <template>
    <group name="Configuration">
      <group name="IMAP">
        <setting name="Server">mail.messagingengine.com</setting>
        <setting name="Port" type="q">993</setting>
        <setting name="Security">SSL/TLS</setting>
      </group>
      <group name="SMTP">
        <setting name="Server">mail.messagingengine.com</setting>
        <setting name="Port" type="q">465</setting>
        <setting name="Security">SSL/TLS</setting>
      </group>
    </group>
  </template>
</service>
`
