### ISSUE TITLE
microsoft translation seems incorrect

### ISSUE THREAD

**Issue by josephholsten** [elementary/switchboard-plug-onlineaccounts#39]
https://github.com/elementary/switchboard-plug-onlineaccounts/blob/master/plugins/OAuth-Subplugins/Microsoft/Microsoft.vala#L34 says:

```vala
            var desc = _("Includes Contacts, Gmail, Google Docs, Google+, YouTube and Picasa");
```

Perhaps this got copied from google?

**Comment by tintou** [comment]
I confirm that it's wrong, the whole mechanism will be reworked
