### ISSUE TITLE
gsignond requires suid to create accounts

### ISSUE THREAD

**Issue by quequotion** [elementary/switchboard-plug-onlineaccounts#76]
First I got this from switchboard-plug-onlineaccounts when clicking on any available type of account to create:
```
 Account.vala:103: GDBus.Error:com.google.code.AccountsSSO.gSingleSignOn.Error.IdentityStoreFailed: Failed to store identity
```

Then I got this when I ran gsignond as an ordinary user:
```
(gsignond:9313): WARNING **: 21:11:42.645: 4312.934444 ../gsignond/src/common/gsignond-storage-manager.c:176 _initialize_storage seteuid() failed

** (gsignond:9313): CRITICAL **: 21:11:42.648: 4312.937226 ../gsignond/src/daemon/gsignond-daemon.c:319 gsignond_daemon_init gsignond_daemon_init_storage() failed

** (gsignond:9313): CRITICAL **: 21:11:42.648: 4312.937303 ../gsignond/src/daemon/db/gsignond-db-metadata-database.c:510 _gsignond_db_metadata_database_open Invalid Metadata DB directory

** (gsignond:9313): CRITICAL **: 21:11:42.648: 4312.937341 ../gsignond/src/common/db/gsignond-secret-storage.c:143 _open_db No directory specified in config object for secret db...

** (gsignond:9313): CRITICAL **: 21:11:42.648: 4312.937367 ../gsignond/src/daemon/gsignond-daemon.c:321 gsignond_daemon_init gisgnond_daemon_open_database() failed
^C
** (gsignond:9313): CRITICAL **: 21:13:44.078: _gsignond_db_sql_database_close: assertion 'self->priv->db != NULL' failed
```

And it occurred to me that gsignond runs with suid; so the DBus service it provides is only availabe to root.

When I ran switchboard with suid, I was able to create accounts with switchboard-plug-onlineaccounts, but I am not sure if that is what I should do. Why doesn't it have an "Unlock" button?

PS: Sorry for the false start; little early on the [Enter] key while typing the title.

**Comment by quequotion** [comment]
Subsequently, accounts added while running switchboard with suid are not accesible to applications running without suid (eg, mail).

**Comment by tintou** [comment]
@quequotion What is your distro, how is gsignond configured ? Basically on elementary we use the `--bus_type=session` and `--extension=desktop` arguments to build it.

**Comment by quequotion** [comment]
@tintou Archlinux; alucryd's package for gsignond only specifies "[documentation='false'](https://github.com/alucryd/aur-alucryd/blob/35eb1a4dbc77159c91048bc1c27dbccbf97a618f/pantheon/gsignond/PKGBUILD#L26)"

I had tried my own buildwith bus_type=session, which didn't work. I had assumed the desktop extension was built by default. I'll try manually specifying both.
