### ISSUE TITLE
"System" doesn't indicate the type of accounts it covers

### ISSUE THREAD

**Issue by uncertainquark** [elementary/switchboard-plug-onlineaccounts#81]
It would be nice if the following account integration options included Calendar in addition to Mail too.

![screenshot from 2017-05-19 22 28 09](https://cloud.githubusercontent.com/assets/22585732/26259755/034e6a8c-3cba-11e7-9c23-570e9ec49c77.png)

**Comment by danrabbit** [comment]
Thanks for your report! We're doing a from-scratch rewrite of Online Accounts and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Online Accounts
